FROM pagerduty-docker.jfrog.io/ubuntu:18.04

RUN apt-get update && \
    apt-get -y install ca-certificates && \
    rm -rf /var/lib/apt/lists/*

COPY dnsmetrics /usr/bin/dnsmetrics

CMD ["/usr/bin/dnsmetrics", "-config", "/local/config.yml"]
