# See also https://circleci.com/docs/2.0/language-go/ 
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/PagerDuty/dnsmetrics
    steps:
      - checkout
      - run: make
